services:
  abernathy-clinic-drnote:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mongo_db_docker
    environment:
      restart: always

  mongo_db_docker:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: