services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27018
      MONGO_DATABASE: abernathy-clinic-drnote
      restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"