spring:
  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/drNotes?authSource=admin
  application:
  name: abernathy-clinic-drnote
#####################
# Actuator Configuration
#####################
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, httpexchanges
#####################
# Server Configuration
#####################
server:
  port: 8082