spring:
  data:
    mongo:
      uri: ${SPRING_DATA_MONGODB_URI | abernathy_clinic}
  application:
  name: abernathy-clinic-drnote
#####################
# Actuator Configuration
#####################
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, httpexchanges
#####################
# Server Configuration
#####################
server:
  port: 8082